name: CI on Self-Hosted Runner

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: arc-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display runner details
        run: |
          echo "Running on $(uname -a)"
          echo "CPU cores: $(nproc)"
          echo "Memory: $(free -h)"
      
      - name: Run a sample job
        run: |
          echo "Hello from self-hosted runner!"
